FROM intel/intel-optimized-tensorflow:1.15.2

ENV http_proxy=http://child-prc.intel.com:913
ENV https_proxy=http://child-prc.intel.com:913
ENV no_proxy=127.0.0.1,localhost,intel.com

WORKDIR /root

COPY requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN rm requirements.txt \
&& rm /intel_tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl

RUN apt update \
&& apt install -y vim

CMD ["/bin/bash"]