# [INTEL CONFIDENTIAL]
# 
# Copyright (c) 2020 Intel Corporation.
# 
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were 
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this
# software or the related documents without Intel's prior written permission.
# 
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

# Config parameters for binary model training

base_model_configs:
    base_model: 'mobilenet'
    base_application: 'MobileNet'
    decoder_filters: 200, 100, 64, 32, 16
    train_csv_path: '../data/train_crop/train.csv'
    val_csv_path: '../data/val_crop/val.csv'
    img_height: 416
    img_width: 416
    batch_size: 10
    lr: 0.002
    lr_sched_drop: 0.5
    epochs: 200
    epochs_drop: 50
    optimizer: 'Adam'
    num_poplayers: 2
    gpu: '0'
    max_workers: 1
    multi_proc: 'True'
    multi_sample_dropout: 'False'
    aug_prob: 0.7
